version: '3.8'

services:
  db:
    build:
      context: .
    image: postgres:13.14-bullseye
    container_name: db
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test_db'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command:
      -p 5432
    restart: unless-stopped

  flyway:
    image: flyway/flyway:10.12.0-alpine
    container_name: flyway
    command:
      -url=jdbc:postgresql://db:5432/test_db
      -user=test
      -password=test
      -schemas=public
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
    external: false
  migration:
    external: false
  data-portainer:
    external: false